project:
  type: website
  output-dir: _site 

website:
  title: "GDCU Quarto Book Website"
  sidebar:
    style: docked
    contents:
      - index.qmd

format:
  html:
    theme: cosmo
    toc: true
