project:
  type: website
  output-dir: _site 

website:
  title: "GDCU Videos Quarto Website"
  sidebar:
    style: "docked"
    contents:
      - index.qmd
      - sections/D1P2.qmd
      - sections/D1P3.qmd
      - sections/D1P4.qmd
      - sections/D2P1.qmd
      - sections/D2P2.qmd
      - sections/D2P3.qmd
      - sections/D2P4.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-location: right
