project:
  type: website
  output-dir: _site 

website:
  title: "GDCU Videos Quarto Book"
  sidebar:
    style: "docked"
    contents:
      - index.qmd
      - section: D1P2.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-location: right
