---
title: "Lesson 1: Data"
author: 
  - "Claudiu Forgaci"
  - "Javier San Millán Tejedor"
  - "Aleksandra Wilczynska"
format: html
---

# [Episode 2: Data Structures](https://carpentries-incubator.github.io/r-geospatial-urban/02-data-structures.html#vectors)

**Videos Credits:** Claudiu Forgaci (Introduction), Javier San Millán Tejedor, Aleksandra Wilczynska

In this episode you're going to start learning about the data structures such as Vectors in the R environment.

## Vectors

Here the data [vectors](https://carpentries-incubator.github.io/r-geospatial-urban/02-data-structures.html#vectors) are explained.

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/afba0847524e4ff197e087b58e17a77e1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Character Vectors

Here the [character vectors](https://carpentries-incubator.github.io/r-geospatial-urban/02-data-structures.html#:~:text=character%5Fvector) are explained.

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/4854fb426b8f4147a1a365fcb0fcf9d21d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Str Vectors

[str() function](https://carpentries-incubator.github.io/r-geospatial-urban/02-data-structures.html#:~:text=str%28character%5Fvector%29) is explained.

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/5bbc79e5f55746a9a6524e5521f5d3751d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question about str function

What does structure function do?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/11a0c88906eb473ca9736397ff20bd071d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

Answer to the question

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/c94ab829a2c7458d8fdb418844f727741d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Combining Vectors

The [combine function, c()](https://carpentries-incubator.github.io/r-geospatial-urban/02-data-structures.html#combining-vectors), is introduced here.

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/6a80b504b4d143c387d9acc78a71e9951d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Tip: Mixed Vectors

Tip on Mixed Vectors and str()

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/8e1b511d587b47cf8437d6146e809d121d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

Additional tips on the Mixed Vectors

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/3f79afe7c01f41e692497ce649ed29731d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question about mixed vectors

What is the underlying rule behind it?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/d422d1f23eb44ebb80d3b6c7e5b813881d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Logical Values

Vectors can also have [logical values](https://carpentries-incubator.github.io/r-geospatial-urban/02-data-structures.html#:~:text=vector%20of%20logical%20values).

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/7a1f70ef1fa24477b976d2fda3dd8c0f1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question about mixing values

What happens when we mix two different types of values?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/d54c95742fbd40b2a3b1efe04f4eb25a1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Missing Values

There will be [missing values.](https://carpentries-incubator.github.io/r-geospatial-urban/02-data-structures.html#missing-values)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/d8f55b70575b4af1958cc64760ab6a851d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Challenge: Missing Values

[Missing Values Part 2](https://carpentries-incubator.github.io/r-geospatial-urban/02-data-structures.html#:~:text=combining%20vectors,-Combine)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/a550ad67d27d489d81d1cf01495604de1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

Missing Values Part 3

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/3b6d9017b54445f085fe3b2140261c161d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Factors

[Factor is another important data structure](https://carpentries-incubator.github.io/r-geospatial-urban/02-data-structures.html#factors).

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/58835b190120475a90155960f1f2b3af1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Creating Factors

Here's how to [create factors](https://carpentries-incubator.github.io/r-geospatial-urban/02-data-structures.html#create-factors).

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/900119a0fab84aefa0d97b2d482481551d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Inspect Factors

The [levels() function](https://carpentries-incubator.github.io/r-geospatial-urban/02-data-structures.html#inspect-factors) is introduced.

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/dd0b519a4fff45b497fe547a238ac7aa1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Tip: Summary function

A tip on using the summary() function

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/367aaa03651d4f75b90c119230918e381d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Reorder levels

[fct_relevel() function](https://carpentries-incubator.github.io/r-geospatial-urban/02-data-structures.html#reorder-levels) is explained.

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/fbe6283821b74dcc95349b8fae022deb1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Questions regarding the syntax

### Question about exclamation mark

What is the use of an exclamation mark inside the syntax?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/6414605e020d4426b7ea6b4f1773f9bd1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

Is it okay to have whitespaces or new lines in R programming?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/178eb1c86a124d3996ce39567dd763fb1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

# [Episode 3: Exploring Data Frames & Data Frame Manipulation with dplyr](https://carpentries-incubator.github.io/r-geospatial-urban/03-explore-data.html#reading-data)

Check the information of data frame basics and explore the dataset.

[**Reading data**](https://carpentries-incubator.github.io/r-geospatial-urban/03-explore-data.html#reading-data)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/8d90123cf284477d900366f8b2ac24dd1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

[**Exploring dataset**](https://carpentries-incubator.github.io/r-geospatial-urban/03-explore-data.html#exploring-dataset)

```{=html}
<iframe title width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/49677d70699545a9912cda18f30184f91d" allowfullscreen msallowfullscreen allow="fullscreen">

</iframe>
```

[**First look at the dataset**](https://carpentries-incubator.github.io/r-geospatial-urban/03-explore-data.html#first-look-at-the-dataset)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/87495c55e71547cf841cfc4c995ecd821d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### The dollar sign

See how to use the dollar sign (\$) in your script.

[**Using dollar sign**](https://carpentries-incubator.github.io/r-geospatial-urban/03-explore-data.html#dollar-sign)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/b85d7dee8914426c863e4d6623da013f1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question about factor function

Can we use factor function to convert character vector?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/0a13097283e54f5c9938a29d86c5a3ff1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

**Answer**

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/7e2a9eaad4764883b65cb8ced17ce3ca1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Tip: Intro to ncol & nrow

An introduction to ncol and nrow functions.

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/35694041a0134b1ea48d21389c2eb6981d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question about summaries

Can we get the summaries for all countries?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/4b001bb148034e2b9b6dcd6fee1806b81d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Dataframe manipulation with dplyr

### Select function

[**Introducing the select function.**](https://carpentries-incubator.github.io/r-geospatial-urban/03-explore-data.html#select)

### Tip: select function errors

When choosing the select function, you may face error saying tidyverse is not installed.

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/f6f19930db774879b91aea1815cd5d3f1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Pipes

[**Introducing the pipe**](https://carpentries-incubator.github.io/r-geospatial-urban/03-explore-data.html#pipe)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/863f48574bd34adb9d5b6211a2d1f7c71d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Tip: read indentations when using pipes

A tip when you're using pipes is to read your code with indentations.

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/56751a83ddcd4559ae14ee5a3accd5531d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question about the pipe

Why use a pipe instead of doing things step by step?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/8bbdd187ceeb428d91a2613f7ff2cae01d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Filter

[**Introduction to filter**](https://carpentries-incubator.github.io/r-geospatial-urban/03-explore-data.html#filter)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/bf79939b5b6d4bd688e6dfc5fb28d0341d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question about the order operation

What is the order of operation if we write it based on that structure?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/2d015b7312bd44f9925828eefccbbaf31d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

A follow-up question from the previous question

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/10eebc780a204ce499195875ae8a78ed1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Challenge: Filtered data frame

Challenge [description](https://carpentries-incubator.github.io/r-geospatial-urban/03-explore-data.html#filter:~:text=CHALLENGE%3A-,FILTERED%20DATA%20FRAME,-Write%20a%20single)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/711abc6648cb406aa6fe7174a21027fa1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

Challenge solution

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/55875a3b3acc47ad9de17d2671ec9daf1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

You can also check the alternative solution

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/b60ad5c8dcf04f2cbb52e8d2931f4f171d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

#### Question about the challenge

how to get all info about a country?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/45c92aa449c441919c1468a5159758471d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Group and summarize

Check the detailed descriptions from the carpentries regarding group and summarize with a challenge.

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/45c92aa449c441919c1468a5159758471d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### [Multiple groups and summary variables](https://carpentries-incubator.github.io/r-geospatial-urban/03-explore-data.html#multiple-groups-and-summary-variables)

## Frequencies

[**Introduction to frequencies**](https://carpentries-incubator.github.io/r-geospatial-urban/03-explore-data.html#frequencies)

## Mutate

[**Mutate function**](https://carpentries-incubator.github.io/r-geospatial-urban/03-explore-data.html#mutate)

## Data Visualization

[**Introduction to data visualization**](https://carpentries-incubator.github.io/r-geospatial-urban/04-intro-to-visualisation.html)

```{=html}
<iframe title="GDCU_D1P2_Data_Visual_Intro" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/ece75cd0629441bab1384abe1001727a1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

[Don't forget to take a quick look at the cheatsheet](https://github.com/carpentries-incubator/r-geospatial-urban/blob/main/instructors/cheatsheet/GDCU2025_cheatsheet.pdf)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/117fa28d37bf41789f800d123d9dae711d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

Second part of the data visualization

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/daed8b040a8743198fa3fb679d915d061d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

Third part of the data visualization. Creating a summary plot for the data using the [**mutate function**](https://carpentries-incubator.github.io/r-geospatial-urban/03-explore-data.html#mutate).

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/61205c4b2a06439f85c6b33af505c34a1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question about a continent in the dataset

How did we know there's the continent of America in the dataset?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/dc0b69395a0f4deda06df7ed1ab7c3461d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

fourth part of data visualization, coloring.

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/37a446990d1046199ef79711af3f1c2b1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Color scale

Color scale and viridis function

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/830776c1da5740d5884fac2e50ef8cb71d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Writing data

[**Saving the plot**](https://carpentries-incubator.github.io/r-geospatial-urban/04-intro-to-visualisation.html#saving-the-plot)

[**Using help documentation**](https://carpentries-incubator.github.io/r-geospatial-urban/04-intro-to-visualisation.html#using-help-documentation)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/894b2ec6611c48ebbe796397d07ffe1f1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Saving the data

[**write.csv function description.**](https://carpentries-incubator.github.io/r-geospatial-urban/04-intro-to-visualisation.html#saving-the-data)

Also, check the cheatsheet.

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/f5bb4878663a42b1957ec864bb34688b1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```
