---
title: "Lesson 2: Vector Data"
author: 
  - "Ana Petrović"
  - "Claudiu Forgaci"
format: html
---

# [Episode 5: Introduction to Geospatial Concepts](https://carpentries-incubator.github.io/r-geospatial-urban/05-intro-to-geospatial-concepts.html)

**Videos Credits:** Claudiu Forgaci, Ana Petrović

Here's a short introduction to geospatial concepts.

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/13d92e5bdb844e40a1812700d2ff078f1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Shape of the Earth

[The shape of the earth](https://carpentries-incubator.github.io/r-geospatial-urban/05-intro-to-geospatial-concepts.html#the-shape-of-the-earth)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/ec18514c943c434f995f815fbfcecbd31d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Map Projections

[Map projection: From the 3D Earth to a 2D map](https://carpentries-incubator.github.io/r-geospatial-urban/05-intro-to-geospatial-concepts.html#map-projection-from-the-3d-earth-to-a-2d-map)

```{=html}
<iframe title width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/49677d70699545a9912cda18f30184f91d" allowfullscreen msallowfullscreen allow="fullscreen">

</iframe>
```

### Coordinate reference systems

[**Coordinate reference systems (CRS)**](https://carpentries-incubator.github.io/r-geospatial-urban/05-intro-to-geospatial-concepts.html#coordinate-reference-systems-crs)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/5f838e743fc449c386213c0e8a5715b01d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Map scale

Check the variations of map scales.

[**Map scale**](https://carpentries-incubator.github.io/r-geospatial-urban/05-intro-to-geospatial-concepts.html#map-scale)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/0381f2a4c5de4c3dbdbebcf5fb5e91401d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Types of geospatial data

Exploring the [**geospatial data categories**](https://carpentries-incubator.github.io/r-geospatial-urban/05-intro-to-geospatial-concepts.html#types-of-geospatial-data).

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/f0a293e571024ae8b43e92fbeb023f571d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Challenge: CRS for calculating areas

The challenge is described as [CRS for calculating areas](https://carpentries-incubator.github.io/r-geospatial-urban/05-intro-to-geospatial-concepts.html#types-of-geospatial-data:~:text=CRS%20FOR%20CALCULATING%20AREAS) and calculating the shortest path.

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/2f772331d0ea4b0a90c62f669c4588af1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

#### Solution

The solutions are explained.

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/354299eb27074408828bca56f46921101d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

# [Episode 6: Open and Plot Vector Layers](https://carpentries-incubator.github.io/r-geospatial-urban/06-open-and-plot-vector-layers.html)

## SF package introduction

[sf package introduction and installation](https://carpentries-incubator.github.io/r-geospatial-urban/06-open-and-plot-vector-layers.html)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/f283aab223e74570bc8714cf9a8d97681d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Geometry in QGIS and R

A description of [geometry in QGIS & R](https://carpentries-incubator.github.io/r-geospatial-urban/06-open-and-plot-vector-layers.html#spatial-metadata)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/f7619c7de4b546d388c4e0b3072e122b1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Import shapefiles

[Import the shp files](https://carpentries-incubator.github.io/r-geospatial-urban/06-open-and-plot-vector-layers.html#import-shapefiles) and opening them using st_read()

```{=html}
<iframe title="GDCU_D1P3_Import_shp" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/9db16df5374f4de0b1b90e885d6d4fef1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question about shapefile metadata

What was the mistake in importing shp?\
loading the wrong dataset

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/d5096f0631b44d0e90051d2d9a19becf1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Assign Data to Object

We can [assign the existing data to an object in R](https://carpentries-incubator.github.io/r-geospatial-urban/06-open-and-plot-vector-layers.html#:~:text=boundary%5FDelft%20%3C%2D%20st%5Fread%28%22data%2Fdelft%2Dboundary%2Eshp%22%2C%20quiet%20%3D%20TRUE%29)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/e4419d613f2642418665972d5e80e0a81d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Spatial Metadata

Here you can use the [st_geometry_type()](https://carpentries-incubator.github.io/r-geospatial-urban/06-open-and-plot-vector-layers.html#spatial-metadata) to read the geometry

```{=html}
<iframe title="GDCU_D1P3_st_Geometry_Type" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/bd2b9d5fb4244e568b3e1bf1c19b0a791d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

With the [**st_crs() function**](https://carpentries-incubator.github.io/r-geospatial-urban/06-open-and-plot-vector-layers.html#:~:text=st%5Fcrs%28%29) you can read the CRS of your data

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/37d2c5c98ca44a09ba93396a951c13411d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question about changing the CRS

Can we change the CRS of a shapefile?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/69c783ed4a814d38975d1958b7811fbd1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## st_transform & bbox functions

[st_transform()](https://carpentries-incubator.github.io/r-geospatial-urban/06-open-and-plot-vector-layers.html#:~:text=st%5Ftransform%28%29) and [st_bbox()](https://carpentries-incubator.github.io/r-geospatial-urban/06-open-and-plot-vector-layers.html#:~:text=st%5Fbbox%28%29) functions are introduced

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/80b9658c92734811a9fbbaee0a4a41f01d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Plot a vector layer

[**plot the vector**](https://carpentries-incubator.github.io/r-geospatial-urban/06-open-and-plot-vector-layers.html#plot-a-vector-layer)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/9e64c8b713de418b9ac235937f0cb2b31d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question about the output

Is the output in British?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/e65a9f5d7b69408183737ec27f8807191d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Plot the vector layer Pt. 2

[**Plot the vector part 2**](https://carpentries-incubator.github.io/r-geospatial-urban/06-open-and-plot-vector-layers.html#plot-a-vector-layer)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/36fb8fae8e1844edb6dc5f83d923ea901d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Challenge: Import line and point vector layers

Challenge [described](https://carpentries-incubator.github.io/r-geospatial-urban/06-open-and-plot-vector-layers.html#plot-a-vector-layer:~:text=IMPORT%20LINE%20AND%20POINT%20VECTOR%20LAYERS)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/a23d5a31ccfa4810b42c31768dd8806b1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

Challenge solution explained

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/8a55014ece9f43a5a6488524bbf46b461d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question about the GUI

Does it make a difference to open (double-click) a file using the GUI?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/d35b9712c52347bab7f5ec2e1e1e57751d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

Solution part 2

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/6641de1cd9e94d6f949f096521d938761d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

# [Episode 7: Explore and plot by vector layer attributes](https://carpentries-incubator.github.io/r-geospatial-urban/07-explore-and-plot-by-vector-layer-attributes.html)

## Query Vector Feature Metadata

[Have a look at the metadata of the layer](https://carpentries-incubator.github.io/r-geospatial-urban/07-explore-and-plot-by-vector-layer-attributes.html)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/41ddeb2adc1f42188f12ea7de08189281d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Explore values

[**Explore values within an attribute**](https://carpentries-incubator.github.io/r-geospatial-urban/07-explore-and-plot-by-vector-layer-attributes.html#explore-values-within-one-attribute)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/af6c63a0571d4a8e974290cc08d0392e1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question about updating the columns

How could the column be updated?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/92b0f62ab8454a4db16d4bf07e716b5e1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Subset features

[**Filter function**](https://carpentries-incubator.github.io/r-geospatial-urban/07-explore-and-plot-by-vector-layer-attributes.html#subset-features)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/0d6bd70e37714675a6fb103e5a170c1a1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

[**Filter function part 2**](https://carpentries-incubator.github.io/r-geospatial-urban/07-explore-and-plot-by-vector-layer-attributes.html#subset-features)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/d0fc0a95500c4525980d6234d83b63d01d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Challenge: Now with the motorways

Challenge [description](https://carpentries-incubator.github.io/r-geospatial-urban/07-explore-and-plot-by-vector-layer-attributes.html#subset-features:~:text=Challenge%3A-,Now%20with%20motorways,-Create%20a%20new)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/f04769eb5a7445cfb5a57f008d5e52461d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

Challenge solution

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/5765d34e8d2d44c6a88ff6de7c042fb51d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

Challenge solution part 2

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/0441c8e72865462db76291894de8c12c1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question about the summarize length

Summarize length, would you also get a simple feature?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/0c9f2dd1ce8f4d6d8d5571e5eeda40011d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Customize plots

[**Introduction to plot customization**](https://carpentries-incubator.github.io/r-geospatial-urban/07-explore-and-plot-by-vector-layer-attributes.html#customize-plots)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/e4a43dc035f44201b74f88d8ff3cb6dc1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Tip: Importance of CRS in plotting

The importance of CRS in plotting your data.

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/f18fcd9c4a9e43c2a37bfba9104d16ec1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

Plot customization part 2

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/aaff2c745fee4363beb85f98551f28981d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question about the levels specifications

Why do we need to specify the levels?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/01ac9cb2306b42e6970f2a0bb2e9f5ee1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

#### Answers

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/1db65d02001c4d49b47c06c954bfab3d1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Examining and coloring objects

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/66e1a508998d4bfe9cfc00842ef6075a1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question about the number of colors

How should we know how many colors we need for the road types?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/1bf9a05123544d49b761d2c42412eaa51d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question about the color order

Is the order of colors the same as the value orders?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/611814937a8e4abd9e9359d61ffbb9201d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```
