---
title: "Lesson 3: Raster Data"
format: html
---

# [Episode 10: Intro to Raster Data](https://carpentries-incubator.github.io/r-geospatial-urban/10-intro-to-raster-data.html)

Starting from this episode, you'll start to work with raster data in R.

## Make sure that you have installed the necessary packages

Check that you have the [terra package installed](https://carpentries-incubator.github.io/r-geospatial-urban/10-intro-to-raster-data.html#:~:text=install%2Epackages%28%22terra%22%29) in your Rstudio environment.

## Raster Script

[Raster script review](https://carpentries-incubator.github.io/r-geospatial-urban/10-intro-to-raster-data.html#view-raster-file-attributes)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/0020734405b2459b839a1c24d2e0bc721d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question about scripting

Is there a way to autosave the script without us having to remember to save it?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/18ac98d1788147818716510ea6738fb41d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Raster Attribute

[describe() function](https://carpentries-incubator.github.io/r-geospatial-urban/10-intro-to-raster-data.html#:~:text=describe%28%29) is introduced

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/93a21b493cad43a79936c8ffa2fea8321d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question about Raster Attribute

Can we use 'here'?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/7cfd9b466da940b29ad8893df81581791d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Raster Attribute Pt.2

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/63f1009db2d34a4a8671b978626368f01d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Open Raster in R

[Import the raster data into R](https://carpentries-incubator.github.io/r-geospatial-urban/10-intro-to-raster-data.html#open-a-raster-in-r)

```{=html}
<iframe title="GDCU_D2P1_Open_Raster_Summary" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/51dfa32c718844a0a24a641326d3f8ff1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question about opening a raster file

Is the height based on the sea level?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/58d52ae5bd1848bd904b30764eff979d1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Open a Raster in R Pt. 2

Using the rast() and summary() functions.

```{=html}
<iframe title="GDCU_D2P1_Open_Raster_Summary_Pt.3" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/e67bd4bfe945482680fb44a61b90c0641d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question about raster summary

What are min and max numbers?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/9ed2260ad596405b8187392f36f484141d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Open a Raster in R Pt. 3

plot and as.data

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/9f1e1bd2310a45938d213bf162fc07fd1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Tip: Close the copilot

Here's how to close the copilot

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/4bc7cf84268a4c84a51b2177ae41ab751d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Open a Raster in R Pt. 4

Common errors of uppercase and lowercase letters during the previous challenge

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/316d5fb1a0bf4abf944e7464ad8913951d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question about putting marks in the argument

What would happen if we don't put the strange marks for our fill argument?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/0dd5cad5f60548a693094092d72eec301d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

Answer to the question

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/7470fddf22884620b2009366c73095b51d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Open a Raster in R Pt. 5

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/9a6ae08400d74503bedad418b84e8d7a1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## View Raster CRS

[Here's how to view the raster coordinate reference system](https://carpentries-incubator.github.io/r-geospatial-urban/10-intro-to-raster-data.html#view-raster-coordinate-reference-system-crs)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/6bcf6c5fdcf04d2289c1e8f8381a34d41d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Calculate Raster's Minimum and Maximum Values

Here's how to [calculate your raster's Min and Max values](https://carpentries-incubator.github.io/r-geospatial-urban/10-intro-to-raster-data.html#calculate-raster-min-and-max-values) with minmax() function

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/7c79b976d82448ea9109f729a87c250e1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question about minmax

How does minmax work in terms of data structure?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/67ac74842d9d4ee09af8e12a19cdb4f21d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Discussion regarding the minmax

Check the [callout for data tip](https://carpentries-incubator.github.io/r-geospatial-urban/10-intro-to-raster-data.html#:~:text=Data%20tip%20%2D%20Set%20min%20and%20max%20values)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/2f33c256a2d64c2faecd50e988435c911d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Raster bands

Raster layers can contain [several band layers of different values](https://carpentries-incubator.github.io/r-geospatial-urban/10-intro-to-raster-data.html#raster-bands).

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/3e7f343111b04b22bff828d5dea8445a1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Challenge: Describe raster values

[Challenge description](https://carpentries-incubator.github.io/r-geospatial-urban/10-intro-to-raster-data.html#creating-a-histogram-of-raster-values)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/42599d383ca84db8bbd31618192ae6ab1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

Challenge solution

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/d1a02fd04227489db6a82ebdc7aa266e1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question about the challenge

Where can we find the information?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/a99cfde0b62f4a50b52b1e0e4a6fcfbd1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

# [Episode 11: Plot Raster Data](https://carpentries-incubator.github.io/r-geospatial-urban/11-plot-raster-data.html)

Introduction to plotting the raster data

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/9658562581b449b992328bfb20eadb391d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Make sure that you have installed the necessary packages

Check that you have the [terra package installed](https://carpentries-incubator.github.io/r-geospatial-urban/10-intro-to-raster-data.html#:~:text=install%2Epackages%28%22terra%22%29) in your Rstudio environment.

## Plotting data using breaks

Using the [cut() and mutate() functions](https://carpentries-incubator.github.io/r-geospatial-urban/11-plot-raster-data.html#plotting-data-using-breaks)

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/9aa3a14e7d2d48a8bddcad1fd65b18641d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question about using breaks

What columns does the data frame have now?

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/b591c8a14edc4dd482b44329b2323b721d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Plotting data using breaks Pt. 2

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/1357b5c315f94deba91ba7924e46d4cc1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Plot Formatting

[There are more plot formatting options](https://carpentries-incubator.github.io/r-geospatial-urban/11-plot-raster-data.html#more-plot-formatting), such as color_scale_fill_manual() function.

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/91107cf989094cdebc3525f393d59c0f1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Plot Formatting Pt. 2

[element_blank() and theme() functions](https://carpentries-incubator.github.io/r-geospatial-urban/11-plot-raster-data.html#:~:text=element%5Fblank%28%29%20to%20the%20axis%2Etitle%20argument%20in%20the%20theme%28%29%20function) are explained.

```{=html}
<iframe title="" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/906512be30da44a18e9dbf67e23994331d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Tip and question about plot formatting

How to check documentation for the theme function?

```{=html}
<iframe title="GDCU_D2P1_T_Q_Plot_Formatting_2.1" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/6ebbfdff830c47dfb6fc545486df3bbb1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

## Challenge: Plot using custom breaks

[Challenge description](https://carpentries-incubator.github.io/r-geospatial-urban/11-plot-raster-data.html#:~:text=Challenge%3A%20Plot%20Using%20Custom%20Breaks)

```{=html}
<iframe title="GDCU_D2P1_C_Plot_Custom_Breaks" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/fa33e8b183d149128e1180d5f5014dc01d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

Challenge Solution

```{=html}
<iframe title="GDCU_D2P1_C_Custom_Breaks_Pt.2" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/4a40d45aec9240d4b202e7e824f841bb1d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```

### Question regarding the challenge

Can you cut the equal numbers of values?

```{=html}
<iframe title="GDCU_D2P1_C_Q_Plot_Custom_Breaks_Pt.2.1" width="700" height="500" frameborder="0" scrolling="auto" marginheight="0" marginwidth="0" src="https://collegerama.tudelft.nl/Mediasite/Play/fbab30bcfd394b658194af14c9e659551d" allowfullscreen msallowfullscreen allow="fullscreen"></iframe>
```
